about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("new/", views.new_post, name="new_post"),
    path("<str:username>/", views.profile, name="profile"),
    path("<str:username>/<int:post_id>/", views.post_view, name="post"),
    path("<str:username>/<int:post_id>/edit/",
         views.post_edit, name='post_edit'),
    path("", views.index, name="index"),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    #  регистрация и авторизация
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),

    #  раздел администратора
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path('about/', include('about.urls', namespace='about'))
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200, verbose_name="Имя сообщества",
        help_text="Не более 200 символов")
    description = models.TextField(
        verbose_name="Описание",
        help_text="Все что объединяет членов этого сообщества")
    slug = models.SlugField(
        unique=True, verbose_name="Адрес",
        help_text="Уникальный адрес группы, он будет частью URL")

    class Meta:
        verbose_name = "Сообщество"
        verbose_name_plural = "Сообщества"

    def __str__(self):
        return str(self.title)


class Post(models.Model):
    text = models.TextField(
        verbose_name="Текст", help_text="Содержание поста")
    pub_date = models.DateTimeField(
        "Дата публикации", auto_now_add=True,
        help_text="Введите дату. По умолчанию будет присвоена текущая.")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts",
        verbose_name="Автор", help_text="Кто написал этот пост?")
    group = models.ForeignKey(
        Group, on_delete=models.SET_NULL, blank=True, null=True,
        related_name="posts", verbose_name="Сообщество",
        help_text="К какому сообществу отнести этот пост?")

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ['-pub_date']

    def __str__(self):
        return str(self.text[:15])

users/models.py
# from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['group', 'text']

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ("first_name", "last_name", "username", "email")

about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/about_author.html'


class AboutTechView(TemplateView):
    template_name = 'about/about_tech.html'

posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.core.paginator import Paginator

from .models import Post, Group, User
from .forms import PostForm

POSTS_PER_PAGE = 10


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(
        request, "index.html",
        {"page": page, "paginator": paginator}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(
        request, "group.html",
        {"group": group, "page": page, "paginator": paginator}
    )


@login_required
def new_post(request):
    form = PostForm(request.POST or None)
    form_title = "Добавить запись"
    if request.method == "POST" and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect("index")
    return render(request, "new.html",
                  {"form": form, "form_title": form_title})


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, pk=post_id)
    if request.user.username != username:
        raise Http404('Вы не являетесь автором этого поста')
    if request.method == "POST":
        form = PostForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()
            return redirect("post", post.author, post.id)
    form = PostForm(instance=post)
    form_title = "Редактировать запись"
    context = {"form": form, "post": post, "form_title": form_title}
    return render(request, "new.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    viewer = request.user.username
    post_list = author.posts.all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    context = {"author": author, "viewer": viewer,
               "page": page, "paginator": paginator}
    return render(request, "profile.html", context)


def post_view(request, username, post_id):
    viewer = request.user.username
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, author=author, pk=post_id)
    post_list = author.posts.all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    context = {"author": author, "viewer": viewer,
               "post": post, "post_id": post_id, "paginator": paginator}
    return render(request, "post.html", context)

users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("signup")
    template_name = "signup.html"

templates/about/about_author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Об авторе
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Меня зовут Алексей Буров. Я работаю в SAP. 
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>Осваиваю Python.</p>
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

templates/about/about_tech.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об используемых технологиях{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Учиться, учиться, учиться!
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Этот проект сделан с помощью костылей и какой-то матери.
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>Терпеть не могу HTML</p>
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>  
</head>

<body>
    {% include 'inclusions/nav.html' %}
    <main>
        <div class="container">
            <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'inclusions/footer.html' %}
</body>

</html>

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
    <p>{{ group.description }}</p>
    <!--  {% include "posts_list.html" with page=page %}>   -->
    {% for post in page %}
    <h3>
        Автор: {{ post.author.get_full_name }}, дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    
    {% include "inclusions/paginator.html" %}    
{% endblock %}

templates/inclusions/author_card.html
<div class="col-md-3 mb-3 mt-1">
    <div class="card">
            <div class="card-body">
                    <div class="h2">
                            <!-- Имя автора -->
                            {{ author.get_full_name }}
                    </div>
                    <div class="h3 text-muted">
                            <!-- username автора -->
                            @{{ author.username }}
                    </div>
            </div>
            <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                            <div class="h6 text-muted">
                                    Подписчиков: XXX <br />
                                    Подписан: XXX
                            </div>
                    </li>
                    <li class="list-group-item">
                            <div class="h6 text-muted">
                                    <!--Количество записей -->
                                    Записей: {{ paginator.count }}
                            </div>
                    </li>
            </ul>
    </div>
</div>

templates/inclusions/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a> 
      </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span 
style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer> 

templates/inclusions/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            Пользователь: {{ user.username }}.
            <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
            <a class="p-2 text-dark" href="{% url 'new_post' %}">Новый пост</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
            <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/inclusions/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/inclusions/post_card.html
<div class="card mb-3 mt-1 shadow-sm">
    <div class="card-body">
            <p class="card-text">
                    <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                    <a href={% url 'profile' username=author.username %}<strong class="d-block text-gray-dark">@{{ author.username }}</strong></a>
                    <!-- Текст поста -->
                    {{ post.text|linebreaksbr }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group ">
                            <!-- Ссылка на редактирование, показывается только автору записи -->
                            {% if author.username == viewer %}
                            <a class="btn btn-sm text-muted" href={% url 'post_edit' username=author.username post_id=post_id %} role="button">Редактировать</a>
                            {% endif %}
                    </div>
                    <!-- Дата публикации  -->
                    <small class="text-muted">{{ post.pub_date }}</small>
            </div>
    </div>
</div>

templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
<!--     {% include "posts_list.html" with page=page %}   -->
{% for post in page %}
<h3>
    Автор: {{ post.author.get_full_name }}, дата публикации: {{ post.pub_date|date:"d M Y" }}
</h3>
<p>{{ post.text|linebreaksbr }}</p>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}

{% include "inclusions/paginator.html" %}

{% endblock %}

templates/new.html
{% extends "base.html" %}
{% block title %}Новая запись{% endblock %}
{% block header %}Ваш новый пост{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form> 
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% block title %}Просмотр поста{% endblock %}
{% block content %}
<main role="main" class="container">
        <div class="row">
                {% include "inclusions/author_card.html" with author=author paginator=paginator%}
                <div class="col-md-9">

                        <!-- Пост -->  
                {% include "inclusions/post_card.html" with post=post post_id=post_id author=author viewer=viewer%}
                </div>
        </div>
</main>
{% endblock %}

templates/posts_list.html
{% for post in page %}
<h3>
    Автор: {{ post.author.get_full_name }}, дата публикации: {{ post.pub_date|date:"d M Y" }}
</h3>
<p>{{ post.text|linebreaksbr }}</p>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}

{% include "inclusions/paginator.html" %}

templates/profile.html
{% extends "base.html" %}
{% block title %}Страница автора {{ author.get_full_name }}{% endblock %}
{% block content %}
<main role="main" class="container">
    <div class="row">
            {% include "inclusions/author_card.html" with author=author paginator=paginator %}

            <div class="col-md-9">                
                {% for post in page %}
                <!-- Начало блока с отдельным постом --> 
                {% include "inclusions/post_card.html" with author=author viewer=viewer post=post post_id=post.id %}
                <!-- Конец блока с отдельным постом --> 
                <!-- Остальные посты -->  
                {% endfor %}
                <!-- Здесь постраничная навигация паджинатора -->
                {% include "inclusions/paginator.html" with paginator=paginator %}

     </div>
    </div>
</main>
{% endblock %}

users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
                
              {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>                
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}